import { createMetadata, LdJson } from "./metadata";
import UniversalFooter from "@/components/UniversalFooter";
import DynamicLogoSmall from "@/components/Logo-small";
import Link from "next/link";

export async function generateMetadata() {
    return createMetadata();
}

export const dynamic = "force-static";

export default function LegalPage() {
    return (
        <>
            <LdJson />
            <main className="min-h-screen flex items-center justify-center px-5 py-10 pb-20 bg-white">
                <div className="w-full max-w-[600px]">
                    <div className="mb-3">
                        <DynamicLogoSmall locale="en" showDivider={false} />
                    </div>
                    <h1 className="font-['Geist'] text-xl md:text-3xl text-black font-bold mb-6">Legal</h1>

                    <section className="mb-8">
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            <b>The Hear</b> is a nonprofit news observatory and archive. The service displays headline data from external news sources for monitoring and comparative analysis. <b>The Hear</b> does not produce independent reporting on covered events. Instead, it lays bare editorial priorities chosen by editors in the source publications. <br /> This page explains our terms of use, how we collect headline data, our copyright approach, our privacy practices, and how to contact us.
                        </p>
                    </section>

                    <section className="mb-8 border-t border-gray-300 pt-6">
                        <h2 className="font-['Geist'] text-xl text-black mb-3">Terms of Use</h2>
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            By using this site, you agree not to misuse the service, interfere with operations, or attempt to access restricted systems. <b>The Hear</b> provides archival and analytical tools for informational purposes and does not guarantee uninterrupted availability or complete coverage of every source at all times. You are responsible for how you use information on this site. <b>The Hear</b> is provided on an &quot;as is&quot; and &quot;as available&quot; basis.
                        </p>
                    </section>

                    <section className="mb-8 border-t border-gray-300 pt-6">
                        <h2 className="font-['Geist'] text-xl text-black mb-3">How We Collect Headline Data</h2>
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            <b>The Hear</b> automatically collects and updates front-page headline metadata from external news publishers. It does so continuously with a system of web-crawlers. We respect robots.txt files and access boundaries where applicable. Sites that actively block algorithmic access are not tracked.
                            <br /> Our scope is intentionally narrow: we only track main headlines and temporal changes across sources and countries. We link to the source article, paywalled or not, for further reading. While the sources can change their headlines later, <b>the Hear</b> provides a time-stamped record of the headline as it was in real time. We use this data to build historical archive pages and cross-source comparisons by country and date, and to generate AI overviews of headline patterns. The AI overviews, generated by large language models, may contain errors. 
                        </p>
                    </section>

                    <section className="mb-8 border-t border-gray-300 pt-6">
                        <h2 className="font-['Geist'] text-xl text-black mb-3">Copyright and Source Rights</h2>
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            <b>The Hear</b> does not claim ownership of publisher headlines, article text, images, logos, or other source content; all intellectual property rights remain with original publishers. Our archive is an attribution and monitoring layer that identifies sources and links users to original publisher URLs. <b>The Hear</b> does not republish full source articles; it records publicly available, headline-level records, timestamped. If you represent a source and have rights-related concerns, contact us with affected URL(s) and we will review in good faith.
                        </p>
                    </section>

                    <section className="mb-8 border-t border-gray-300 pt-6">
                        <h2 className="font-['Geist'] text-xl text-black mb-3">Privacy</h2>
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            We use standard analytics and infrastructure logs to operate, monitor, and improve the service; this may include technical data such as IP address, browser type, device details, and requested URLs. We do not sell personal data. Data may be processed by service providers used for hosting, analytics, and reliability or security operations. If you contact us by email, we use the information you provide to respond to your request. Data retention periods can vary by subsystem according to operational and security requirements.
                        </p>
                    </section>

                    <section className="border-t border-gray-300 pt-6">
                        <h2 className="font-['Geist'] text-xl text-black mb-3">Contact</h2>
                        <p className="font-['Geist'] text-xs text-gray-800 leading-6">
                            Questions about these terms, privacy, or rights-related concerns can be submitted via
                            {" "}
                            <Link href="/contact" className="text-blue-600 hover:text-blue-700 underline">
                                the contact form
                            </Link>
                            {" "}
                            or sent to
                            {" "}
                            <a
                                href="mailto:info@the-hear.com"
                                className="text-blue-600 hover:text-blue-700 underline"
                            >
                                info@the-hear.com
                            </a>
                        </p>
                    </section>

                    <p className="font-['Geist'] text-xs text-gray-400 mt-8 font-mono">
                        Last updated at February 26, 2026
                    </p>
                </div>
            </main>
            <UniversalFooter locale="en" pageType="legal" />
        </>
    );
}
